// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxR3_6wsLe2r6an3xW160GaXlL-v13FsA',
    appId: '1:834707577867:web:8a877f3ac91282f63fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    authDomain: 'fire-learn-5388f.firebaseapp.com',
    storageBucket: 'fire-learn-5388f.appspot.com',
    measurementId: 'G-KBCR6E7NDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsBAnpYIXtCm2OEptv8czE8P3z_rKLVdY',
    appId: '1:834707577867:android:a460ff83dff948833fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    storageBucket: 'fire-learn-5388f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3B2YlePw5ENmhFop2weOrrUrapwdUDa8',
    appId: '1:834707577867:ios:ae5183379089a7683fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    storageBucket: 'fire-learn-5388f.appspot.com',
    iosBundleId: 'com.example.dirdashly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxR3_6wsLe2r6an3xW160GaXlL-v13FsA',
    appId: '1:834707577867:web:9622811160d174733fbb0e',
    messagingSenderId: '834707577867',
    projectId: 'fire-learn-5388f',
    authDomain: 'fire-learn-5388f.firebaseapp.com',
    storageBucket: 'fire-learn-5388f.appspot.com',
    measurementId: 'G-LD8LT9MJSD',
  );
}
